### ISSUE TITLE
Nothing happens on clicking competitive companion icon

### ISSUE THREAD

**Issue by Dayal-Kumar** [Pushpavel/AutoCp#110]
**Describe the bug**
When I click on the competitive companion icon, it should result in opening of a popup in clion but it doesn't. I have tested the competitive companion extension with cphelper in vscode and cpeditor too, they work fine. 

**To Reproduce**
1. Go to any problem site like codeforces.com, open a problem page.
2. Click on Competitive Companion Icon.
3. Go to CLION
4. No popups, no errors, nothing.

**Expected behavior**
A popup should open, or a new file should be created automatically.

**Environment (please complete the following information):**
 - OS: MacOS Arm64
 - IDE: CLION
-  Programming Language: C++

**Comment by Dayal-Kumar** [comment]
Works fine with 2022.2.4 but not in 2022.3.1
Seems to be compatibility issue.

**Comment by Pushpavel** [comment]
You should open CLION first before clicking on Competitive companion icon and I checked with CLION 2022.3.1 (CL-223.8214.51 / Lastest snapshot build) which works fine.

**Comment by Dayal-Kumar** [comment]
Yes I did so, and it worked a few times in CLION 2022.3.1, and the plugin would randomly crash a few times, then I had to restart CLION. So, it did not work consistently for me.

**Comment by Pushpavel** [comment]
This is expected when you open any other tools that also work with competitive companion like cphelper, does the crash occur even without opening any of these tools ? If so, there should have been error reporting from CLION about the crash.

**Comment by Dayal-Kumar** [comment]
Yes, I had tried to run it with other tools closed, but it still isn't working. There are no errors either.
<img width="1266" alt="Screenshot 2022-12-26 at 1 21 05 PM" src="https://user-images.githubusercontent.com/83410988/209520889-1832c8e7-c159-451a-8b3d-faf8cf216977.png">

**Comment by Dayal-Kumar** [comment]
Created a new project, it worked for a few times and then this error and it stopped working.

com.intellij.diagnostic.PluginException: 5543 ms to call on BGT precache-slow-data@RunAutoCpAction#update@keyboard shortcut (com.github.pushpavel.autocp.config.actions.RunAutoCpAction). Revise AnAction.getActionUpdateThread property [Plugin: com.github.pushpavel.autocp]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.logTimeProblemForPreCached(ActionUpdater.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.ensureSlowDataKeysPreCached(ActionUpdater.java:484)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$callAction$6(ActionUpdater.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:201)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction(ActionUpdater.java:161)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.updateActionReal(ActionUpdater.java:137)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$new$0(ActionUpdater.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.update(ActionUpdater.java:705)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$UpdateSessionImpl.presentation(ActionUpdater.java:814)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doUpdateActionsInner(IdeKeyEventDispatcher.java:674)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:621)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$15(Utils.java:756)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1086)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.lambda$tryRunReadActionAndCancelBeforeWrite$19(ActionUpdater.java:428)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.tryRunReadActionAndCancelBeforeWrite(ActionUpdater.java:424)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$16(Utils.java:756)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$18(Utils.java:763)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.actionSystem.impl.Utils.lambda$runUpdateSessionForInputEvent$20(Utils.java:762)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:212)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:205)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Pushpavel** [comment]
I think I got where to look for solving this issue. thanks for reporting the error.

**Comment by Pushpavel** [comment]
The issue may have solved, I am not sure as I could not reproduce it, so please try this build.
[AutoCp-v0.7.10.zip](https://github.com/Pushpavel/AutoCp/files/10306819/AutoCp-v0.7.10.zip).

**Comment by Dayal-Kumar** [comment]
Sure, will give feedback after testing.

**Comment by Dayal-Kumar** [comment]
I am facing the same issue. BTW, haven't got that error message again yet.

**Comment by Dayal-Kumar** [comment]
<img width="413" alt="Screenshot 2022-12-27 at 8 27 28 PM" src="https://user-images.githubusercontent.com/83410988/209684144-aedbbc63-1108-4e6a-adfc-7c3475bb893f.png">

**Comment by Pushpavel** [comment]
> <img alt="Screenshot 2022-12-27 at 8 27 28 PM" width="413" src="https://user-images.githubusercontent.com/83410988/209684144-aedbbc63-1108-4e6a-adfc-7c3475bb893f.png">

when does this occur ?

**Comment by Dayal-Kumar** [comment]
First of all, after installing 0.7.10, it did not work, so I changed to a different project. Worked for once, then after solving a problem, I used Competitive Companion on another problem. Then, I put my laptop to sleep, when turned it on again, this was the popup in CLION.

**Comment by Pushpavel** [comment]
Is this popup coming up again?

**Comment by Dayal-Kumar** [comment]
Yes
