### ISSUE TITLE
I am getting this error while trying to run autocp configuration on clion

### ISSUE THREAD

**Issue by DopDie** [Pushpavel/AutoCp#123]
Error message:
Cannot run program "g++" (in directory "C:\Users\UseR\AppData\Local\Temp\AutoCp17191170129971631139"): CreateProcess error=2, The system cannot find the file specified
Stacktrace:
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "g++" (in directory "C:\Users\UseR\AppData\Local\Temp\AutoCp17191170129971631139"): CreateProcess error=2, The system cannot find the file specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:362)
	at com.github.pushpavel.autocp.tester.base.TwoStepProcessFactory$Companion.from(TwoStepProcessFactory.kt:44)
	at com.github.pushpavel.autocp.tester.base.TwoStepProcessFactory$Companion$from$1.invokeSuspend(TwoStepProcessFactory.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: Cannot run program "g++" (in directory "C:\Users\UseR\AppData\Local\Temp\AutoCp17191170129971631139"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:438)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:352)
	... 8 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 11 more

**Comment by Pushpavel** [comment]
This is similar to #15 , basically you need g++ to be installed on your system.
