### ISSUE TITLE
Cannot run AutoCP

### ISSUE THREAD

**Issue by Mikami382** [Pushpavel/AutoCp#64]
**Describe the bug**
Can't run it at all. I enabled it on my file and tried to run it (alt - x). It said "Cannot run on debug". So I figured that I would have to manually edit the run/debug configuration myself and add AutoCP configuration and select my file as "Solution File"

**Screenshots**
![image](https://user-images.githubusercontent.com/16867718/148632469-258eff66-febe-4d29-8e6f-faf5110de4f4.png)

Error message:
`Testing started at 12:11 PM ...
Building "2" ...
This was not supposed to happen, please file an <a herf="https://github.com/Pushpavel/AutoCp/issues/new/choose">issue</a>

Error message:
Cannot run program "g++" (in directory "C:\Users\Asus\AppData\Local\Temp\AutoCp1867462911877868614"): CreateProcess error=2, The system cannot find the file specified
Stacktrace:
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "g++" (in directory "C:\Users\Asus\AppData\Local\Temp\AutoCp1867462911877868614"): CreateProcess error=2, The system cannot find the file specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:364)
	at com.github.pushpavel.autocp.tester.base.TwoStepProcessFactory$Companion.from(TwoStepProcessFactory.kt:43)
	at com.github.pushpavel.autocp.tester.base.TwoStepProcessFactory$Companion$from$1.invokeSuspend(TwoStepProcessFactory.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.io.IOException: Cannot run program "g++" (in directory "C:\Users\Asus\AppData\Local\Temp\AutoCp1867462911877868614"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:440)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:354)
	... 8 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:487)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 11 more
`

**Environment (please complete the following information):**
 - OS: Windows 10
 - IDE: CLion
-  Programming Language: C++

**Comment by Pushpavel** [comment]
This is similar to #15 , basically you need g++ to be installed on your system.
